In [2]:
import numpy as np

In [4]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [6]:
# Convertir de grados a radianes
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
# Funcion seno
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [8]:
# Funcion coseno
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [14]:
numero_random = np.random.randint(
        11 # [0,11[
)
numero_random

7

In [15]:
numero_random_negativo = np.random.randint(
        -9, # [-9,2[
        2
)
numero_random_negativo

-4

In [20]:
arreglo_random = np.random.randint(
        10,
        20,
        8
)
arreglo_random

array([18, 18, 18, 10, 11, 18, 17, 17])

In [21]:
np.random.rand(9)
np.random.rand(3,2)

array([[0.37814682, 0.8387788 ],
       [0.95523479, 0.86572885],
       [0.36964522, 0.70761213]])

In [22]:
# Promedio
np.average(arreglo_random)

15.875

In [23]:
# Media
np.mean(arreglo_random)

15.875

In [24]:
# Mediana
np.median(arreglo_random)

17.5

In [25]:
# Desviacion estandar
np.std(arreglo_random)

3.1399641717701177

In [26]:
# Varianza
np.var(arreglo_random)

9.859375