# 1) Examen

In [ ]:
import numpy as np
import pandas as pd

## 2) Crear un vector de ceros de tamaño 10

In [12]:
ejercicio2 = np.zeros(10)
print(ejercicio2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [13]:
ejercicio3 = np.zeros(10)
#print(ejercicio3)
ejercicio3[4]=1
print(ejercicio3)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [15]:
ejercicio4 = np.arange(50)
#print(respuesta4)
ejercicio4 = ejercicio4[::-1]
print(ejercicio4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [16]:
ejercicio5 = np.arange(9).reshape(3,3)
print(ejercicio5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 6) Encontrar los indices que no sean cero en un arreglo

In [11]:
arreglo = [1,2,0,0,4,0]
indices_no_ceros = np.nonzero(arreglo)
print(f'Los indices que no son cero son {indices_no_ceros}')

Los indices que no son cero son (array([0, 1, 4]),)


## 7) Crear una matriz de identidad 3 x 3 

In [17]:
ejercicio7 = np.eye(3)
print(ejercicio7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [21]:
ejercicio8 = np.random.rand(3,3,3)
print(ejercicio8)

[[[0.76391659 0.06202009 0.90019669]
  [0.22801948 0.27959645 0.76727862]
  [0.33166215 0.29799465 0.74993915]]

 [[0.7712874  0.64550873 0.58642174]
  [0.68396126 0.62394861 0.19876891]
  [0.84996819 0.20715516 0.8326484 ]]

 [[0.71698002 0.29533494 0.4367665 ]
  [0.25809821 0.81129764 0.10493819]
  [0.6694066  0.21913986 0.06502762]]]


## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [22]:
ejercicio9 = np.random.rand(10,10)
mayor = ejercicio9.max()
menor = ejercicio9.min()
print(ejercicio9)
print(f'El numero mayor es {mayor}')
print(f'El numero menor es {menor}')

[[0.38602068 0.39525324 0.01893298 0.25726178 0.13032724 0.00144173
  0.27294537 0.55730205 0.38813755 0.24040805]
 [0.85977086 0.46797455 0.39592232 0.36746637 0.55502637 0.77516222
  0.55381856 0.12575291 0.84155885 0.67779935]
 [0.12746007 0.14767425 0.55814772 0.23777202 0.31856119 0.43935706
  0.99029263 0.22218953 0.85209397 0.70071049]
 [0.71306289 0.20803062 0.10315347 0.35186027 0.07423374 0.63466848
  0.81231983 0.62357207 0.31898295 0.08065561]
 [0.07458023 0.55828581 0.10648833 0.07154219 0.87768046 0.87508018
  0.06629156 0.4178042  0.91976618 0.08668942]
 [0.71474749 0.5729929  0.69172033 0.62149605 0.54452368 0.11617851
  0.96833863 0.1691692  0.78059965 0.83585135]
 [0.30595812 0.48413133 0.63644962 0.75049032 0.99822251 0.02038791
  0.22040977 0.70700673 0.8531558  0.3804966 ]
 [0.72245929 0.94621895 0.29383781 0.51320148 0.65009346 0.49272894
  0.83518053 0.01786351 0.38382917 0.12040452]
 [0.13808678 0.73247203 0.7185815  0.76104783 0.25921521 0.84203941
  0.0800147 

## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [32]:
from scipy import ndimage
from scipy import misc
imagen = misc.face()

rgb_todos = imagen.reshape(imagen.shape[0] * imagen.shape[1], imagen.shape[2])
#print(rgb_todos)
rgb_unicos = np.unique(rgb_todos, axis=0)
print(rgb_unicos)
print(f'Color 1 : {rgb_unicos[-1]}')
print(f'Color 2 : {rgb_unicos[-2]}')

[[  0   0   5]
 [  0   0   7]
 [  0   0   9]
 ...
 [255 248 255]
 [255 249 255]
 [255 252 255]]
Color 1 : [255 252 255]
Color 2 : [255 249 255]


## 11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [35]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_list = pd.Series(mylist)
serie_arr = pd.Series(myarr)
serie_dict = pd.Series(mydict)

#print(serie_list)
#print(serie_arr)
#print(serie_dict)

## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [37]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 

# Transformar la serie en dataframe y hacer una columna indice

df12 = pd.DataFrame(ser)
df12.index = df12[0]
print(df12)

     0
0     
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23
24  24
25  25


## 13) ¿Como combinar varias series para hacer un DataFrame?

In [39]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df13 = pd.DataFrame({'Serie 1': ser1, 'Serie 2': ser2})
print(df13)

   Serie 1  Serie 2
0        a        0
1        b        1
2        c        2
3        e        3
4        d        4
5        f        5
6        g        6
7        h        7
8        i        8
9        j        9
10       k       10
11       l       11
12       m       12
13       n       13
14       o       14
15       p       15
16       q       16
17       r       17
18       s       18
19       t       19
20       u       20
21       v       21
22       w       22
23       x       23
24       y       24
25       z       25


## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [46]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_en_a_y_b = ser1.isin(ser2)
#print(items_en_a_y_b)
items_en_a_y_no_b = ser1[~items_en_a_y_b]
print(f'Los items que están en A y no en B son: \n{items_en_a_y_no_b}')

Los items que están en A y no en B son: 
0    1
1    2
2    3
dtype: int64


## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

In [48]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_en_a_y_no_b = ser1[~ser1.isin(ser2)]
items_en_b_y_no_a = ser2[~ser2.isin(ser1)]
items_no_comunes = np.append(items_en_a_y_no_b, items_en_b_y_no_a)
print(f'Los items no comunes entre a y b son: {items_no_comunes}')

Los items no comunes entre a y b son: [1 2 3 6 7 8]


## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [49]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
num_veces = ser.value_counts()
print(num_veces)

a    7
f    5
d    5
g    4
b    4
e    3
h    1
c    1
dtype: int64


## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [57]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(f'Serie \n{ser}')
num_veces = ser.value_counts()
print(f'\nContador de repeticiones \n{num_veces}')
ser[~ser.isin(ser.value_counts().index[:2])] = 0
print(f'\nSerie cambiada a 0 \n{ser}')

Serie 
0     1
1     4
2     4
3     1
4     4
5     2
6     2
7     4
8     2
9     2
10    1
11    2
dtype: int64

Contador de repeticiones 
2    5
4    4
1    3
dtype: int64

Serie cambiada a 0 
0     0
1     4
2     4
3     0
4     4
5     2
6     2
7     4
8     2
9     2
10    0
11    2
dtype: int64


## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

In [58]:
ser = pd.Series(np.random.randint(1, 10, 35))
shape = (7,5)
df18 = pd.DataFrame(ser.values.reshape(shape))
print(df18)

   0  1  2  3  4
0  6  7  8  3  4
1  9  9  8  5  9
2  9  6  1  8  1
3  1  5  9  8  2
4  4  8  2  4  7
5  4  3  7  4  4
6  5  1  5  7  9


## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

In [59]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

ejercicio19 = ser[pos]
print(ejercicio19)

0     a
4     e
8     i
14    o
20    u
dtype: object


## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

In [83]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

df20A = pd.DataFrame(ser1)
df20B = pd.DataFrame(ser1)

# Añadir series vertical
df20A[1] = ser2
print(df20A)

# Añadir series horizontal
df20B = df20B.append(ser2, ignore_index = True)
print(df20B)


   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
   0    1    2    3    4
0  0  NaN  NaN  NaN  NaN
1  1  NaN  NaN  NaN  NaN
2  2  NaN  NaN  NaN  NaN
3  3  NaN  NaN  NaN  NaN
4  4  NaN  NaN  NaN  NaN
5  a    b    c    d    e


## 21)¿Obtener la media de una serie agrupada por otra serie?

In [72]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

df21 = pd.DataFrame({
        'Frutas': frutas,
        'Pesos': pesos})
df21.groupby(['Frutas']).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'zanahoria', 'manzana', 'banana', 'zanahoria', 'zanahoria', 'zanahoria', 'manzana', 'banana', 'manzana']


Pesos
Frutas          
banana       6.5
manzana      5.5
zanahoria    5.0

## 22)¿Como importar solo columnas especificas de un archivo csv?

In [79]:
# url: https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.

path = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

df22_completo = pd.read_csv(path)
#print(df22_completo)

columnas = ['crim', 'zn','indus', 'age', 'nox']
df22_columnas = pd.read_csv(path,  usecols=columnas)
print(df22_columnas.head())

      crim    zn  indus    nox   age
0  0.00632  18.0   2.31  0.538  65.2
1  0.02731   0.0   7.07  0.469  78.9
2  0.02729   0.0   7.07  0.469  61.1
3  0.03237   0.0   2.18  0.458  45.8
4  0.06905   0.0   2.18  0.458  54.2
